try{
    let car = newCar;
}
catch(error) {
    console.log('Error: ',error);
}
console.log('continuing...')